FROM alpine-java:base
MAINTAINER omnius.com
COPY files/taskmanager-server.jar /opt/spring-cloud/lib/
ENV SPRING_APPLICATION_JSON='{"spring": {"cloud": {"config": {"server": \
    {"git": {"uri": "/var/lib/spring-cloud/config-repo", "clone-on-start": true}}}}}}'
ENTRYPOINT ["/usr/bin/java"]
CMD ["-jar", "/opt/spring-cloud/lib/taskmanager-server.jar"]
VOLUME /var/lib/spring-cloud/config-repo
EXPOSE 8888
